/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.askal.ispbillingsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Lorence
 */
public class BillDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BillDialog.class.getName());
    private Bill bill = null;
    private boolean saved = false;
    private CustomerDAO dao = new CustomerDAO();
    public boolean isSaved() { return saved; }
    public Bill getBill() { return bill; }
        
    public BillDialog(java.awt.Frame parent, boolean modal) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(parent);
        setTitle("Generate Bill");
        bill = new Bill();

        for (Customer c : dao.getAllCustomers()) {
            customerCombo.addItem(c.getId() + " — " + c.getFullName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        customerCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        periodField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dueDateField = new javax.swing.JTextField();
        btnRowPanel = new javax.swing.JPanel();
        cancelBillBtn = new javax.swing.JButton();
        saveBillBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setSize(new java.awt.Dimension(400, 300));

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 8, 16));
        formPanel.setLayout(new java.awt.GridLayout(4, 2, 8, 10));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Customer:");
        formPanel.add(jLabel1);

        customerCombo.addActionListener(this::customerComboActionPerformed);
        formPanel.add(customerCombo);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Period:");
        formPanel.add(jLabel2);
        formPanel.add(periodField);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Amount (₱):");
        formPanel.add(jLabel3);
        formPanel.add(amountField);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Due Date:");
        formPanel.add(jLabel4);
        formPanel.add(dueDateField);

        getContentPane().add(formPanel, java.awt.BorderLayout.CENTER);

        btnRowPanel.setBackground(new java.awt.Color(255, 255, 255));
        btnRowPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 16, 16, 16));
        btnRowPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        cancelBillBtn.setText("Cancel");
        cancelBillBtn.addActionListener(this::cancelBillBtnActionPerformed);
        btnRowPanel.add(cancelBillBtn);

        saveBillBtn.setText("Save");
        saveBillBtn.addActionListener(this::saveBillBtnActionPerformed);
        btnRowPanel.add(saveBillBtn);

        getContentPane().add(btnRowPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBillBtnActionPerformed
        saved = false;
        dispose();
    }//GEN-LAST:event_cancelBillBtnActionPerformed

    private void saveBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBillBtnActionPerformed
        try {
            String selected = (String) customerCombo.getSelectedItem();
            int customerId = Integer.parseInt(selected.split(" — ")[0].trim());
            double amount = Double.parseDouble(amountField.getText().trim());
            java.time.LocalDate dueDate = java.time.LocalDate.parse(dueDateField.getText().trim());

            bill.setCustomerId(customerId);
            bill.setPeriod(periodField.getText().trim());
            bill.setAmount(amount);
            bill.setDueDate(dueDate);
            saved = true;
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please check your inputs.\nDate format: YYYY-MM-DD");
        }
    }//GEN-LAST:event_saveBillBtnActionPerformed

    private void customerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                BillDialog dialog = new BillDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JPanel btnRowPanel;
    private javax.swing.JButton cancelBillBtn;
    private javax.swing.JComboBox<String> customerCombo;
    private javax.swing.JTextField dueDateField;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField periodField;
    private javax.swing.JButton saveBillBtn;
    // End of variables declaration//GEN-END:variables
}
